# clonezilla.conf - Clonezilla Automation Configuration

# Common Clonezilla Configuration Variables
ISO_FILE="clonezilla.iso"
REPOSITORY="dev:///uuid=bbb79c06-4d29-4b73-b0ea-405a1c35de38"
BACKUP_DIR="backup_sys"
TARGET_DISK="nvme0n1"

# Directory where backups are stored (used by restore script to list backups)
FOLDER_REPOS="/srv/dev-disk-by-uuid-bbb79c06-4d29-4b73-b0ea-405a1c35de38/backup_sys"